### PR TITLE
Add Ui.png to /docs/images resolves #14

### LINKED ISSUE #14: README - UI Mock up
Add a UI mockup of your intended final product. Note that the image of the UI should be docs/images/Ui.png so that it can be downloaded by our scripts. Limit the file to contain one screenshot/mockup only and ensure the new image is roughly the same height x width proportions as the original one.

### PR DESCRIPTION
**Pull request by eugenechiaay**

### CODE REVIEW

**Review by shurvirarora — COMMENTED** [review]
Ui mock up image added, LGTM!

**Review by shurvirarora — APPROVED** [review]
Approved.

**Comment by SimJM** [comment]
Nice mock up image, LGTM

**Comment by shurvirarora** [comment]
Fixes #14

**Pull request merged**
