### PR TITLE
Issue #18 - Update Use Cases

### PR DESCRIPTION
**Pull request by SimJM**
Viewing help, Adding a person, Listing all contacts, Locating contacts by name

### CODE REVIEW

**Review by eugenechiaay — APPROVED** [review]
LGTM, will do numbering on my end

**Review by tanweien — APPROVED** [review]
LGTM

**Review by shurvirarora — APPROVED** [review]
Good flow of use cases. 👍 LGTM!

**Comment by shurvirarora** [comment]
Fixes #18

**Pull request merged**
